"""
ANACONDA — light map for the snake (Blender 4.2+ / 5.x)
=======================================================

Rebuilds the level from anaconda_floorplan.py (same folder), then measures the
light falling on a white "probe" plane at the height of the snake's back.
The result is the colour and brightness of the room lighting at every point,
with the floor's own colour taken out, so the snake can be lit exactly like
the floor it crawls over.

Run headless:
    blender --background --python anaconda_lightmap.py

Outputs (next to this script, in anaconda_renders/):
    snake_light.png 192x192 (8 px per tile). Multiply the snake's body by it:
                    sample at world px / 960. GAIN and AMBIENT already applied.
    lightmap.luau   the same colours as a 48x48 Luau table, for the head
    light_map.png   the raw tone-mapped light, for looking at
"""

import bpy
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import anaconda_floorplan as fp  # noqa: E402

PROBE_Z = 0.3          # metres: about the top of the snake's back
PX_PER_TILE = 8        # render resolution; averaged down to SAMPLES_PER_TILE
SAMPLES_PER_TILE = 2   # grid written to lightmap.luau
SOFT = 0.9             # light level that maps to ~63%: raise to darken the whole map
GAIN = 1.8             # how strongly the room light shows on the snake
AMBIENT = (0.16, 0.16, 0.20)  # the darkest the snake ever gets (cool, so it reads as night)


def main():
    fp.clear_scene()
    fp.SAMPLES = int(os.environ.get("ANACONDA_SAMPLES", 64))
    fp.OUTLINES = False
    fp.setup_render()
    sc = bpy.context.scene
    sc.render.use_freestyle = False
    sc.view_settings.view_transform = "Standard"
    sc.view_settings.look = "None"
    sc.render.resolution_x = sc.render.resolution_y = fp.N * PX_PER_TILE

    col_floor = fp.new_collection("FLOOR")
    col_walls = fp.new_collection("WALLS")
    col_lights = fp.new_collection("LIGHTS")
    col_cam = fp.new_collection("CAMERA")
    fp.build_floor(col_floor)
    fp.build_decals(col_floor)
    fp.build_walls(col_walls)
    fp.build_windows(col_walls)
    fp.build_exit(col_walls)
    fp.build_room_lights(col_lights)
    fp.build_camera(col_cam)

    # White probe over the whole level at snake height.
    import bmesh
    half = fp.N * fp.TILE / 2
    bm = bmesh.new()
    fp.quad(bm, -half, -half, half, half, PROBE_Z)
    probe = fp.mesh_obj("probe", bm, col_floor)
    white = fp.flat_material("probe_white", (1.0, 1.0, 1.0), 1.0)
    probe.data.materials.append(white)
    probe.visible_shadow = False  # don't darken the floor bounce under it

    # Floor-level things below the probe stay in the scene for bounce light
    # but the camera only sees the probe (and the walls above it).
    d = fp.out_dir()
    exr = os.path.join(d, "light_map.exr")
    sc.render.image_settings.file_format = "OPEN_EXR"
    sc.render.image_settings.color_depth = "32"
    sc.render.image_settings.color_mode = "RGB"
    fp.render_to(exr)

    import numpy as np

    img = bpy.data.images.load(exr)
    w, h = img.size
    raw = np.array(img.pixels[:], dtype=np.float32).reshape(h, w, img.channels)[::-1, :, :3]

    # Tone-map the brightest channel and scale the others with it, so hot spots
    # keep their colour instead of burning out to white; then turn light into
    # the colour the snake is multiplied by: brightened by GAIN, never darker
    # than AMBIENT (the player must always see their snake), capped at white.
    m = raw.max(axis=2, keepdims=True)
    tone = np.where(m > 1e-6, raw / np.maximum(m, 1e-6) * (1.0 - np.exp(-m / SOFT)), 0.0)
    mod = np.clip(np.maximum(tone * GAIN, np.array(AMBIENT)), 0.0, 1.0)

    def save_png(arr, name):
        hh, ww = arr.shape[:2]
        im = bpy.data.images.new(name, ww, hh)
        rgba = np.concatenate([arr, np.ones((hh, ww, 1))], axis=2)[::-1]
        im.pixels = rgba.astype(np.float32).ravel().tolist()
        im.filepath_raw = os.path.join(d, name + ".png")
        im.file_format = "PNG"
        im.save()

    # Full-resolution multiply map for the body (game: world px / 960 = UV).
    save_png(mod, "snake_light")
    save_png(tone, "light_map")

    # Coarser table for the script (the head samples it).
    k = PX_PER_TILE // SAMPLES_PER_TILE
    G = fp.N * SAMPLES_PER_TILE
    grid = mod.reshape(G, k, G, k, 3).mean(axis=(1, 3))
    q = np.clip(np.round(grid * 255), 0, 255).astype(int)
    hexs = "".join("%02x" % v for v in q.reshape(-1))
    lines = [
        "-- Generated by anaconda_lightmap.py. Do not edit by hand.",
        "-- The colour to multiply the snake by at each point of the level (room lighting",
        "-- with GAIN and the AMBIENT floor applied; same values as snake_light.png).",
        f"-- {G}x{G} samples, {SAMPLES_PER_TILE} per tile, sample centres at (i + 0.5) / {SAMPLES_PER_TILE} tiles, row 0 at the top.",
        "-- `rgb` is a hex string, 2 characters per byte, 3 bytes (R, G, B, 0-255) per sample,",
        "-- row-major: byte k (1-based) = (row * size + col) * 3 + channel. Decode it once at load.",
        "return {",
        f"    size = {G},",
        f"    perTile = {SAMPLES_PER_TILE},",
        f'    rgb = "{hexs}",',
        "}",
        "",
    ]
    with open(os.path.join(d, "lightmap.luau"), "w") as f:
        f.write("\n".join(lines))
    print("[anaconda] light map ->", d)


if __name__ == "__main__":
    main()
